accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='sign-up')
]

ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.IndexView.as_view(), name='home'),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField

# CustomUser model for store customers
class CustomUser(AbstractUser):
    full_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_number = PhoneNumberField()

core/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import CustomUser

class SignUpForm(forms.ModelForm):

    '''
    Customer Sign Up Form - OTP Implemented
    '''

    date_of_birth = forms.DateField(
        widget=forms.SelectDateWidget(years=range(1900, 2025)))
    password = forms.CharField(widget=forms.PasswordInput)
    re_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['full_name', 'date_of_birth',
                  'gender', 'phone_number', 'password', 're_password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        re_password = cleaned_data.get("re_password")

        if password != re_password:
            raise forms.ValidationError(
                "Password don't match - Please try again"
            )

accounts/views.py
from django.shortcuts import render
from django.http import HttpRequest
from .forms import SignUpForm 

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpRequest("Done!")
    else:
        form = SignUpForm()
    return render(request, 'accounts/sign_up.html', {'form': form})    

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class IndexView(TemplateView):
    template_name = 'core/index.html'

accounts/templates/accounts/sign_up.html
{% extends "core/base.html" %}

{% block content %}
    <form method="POST" class="m-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock content %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Title -->
    <title>Ecomm</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <!-- flag-icon-css library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/7.1.0/css/flag-icons.min.css">
  </head>
  <body>
    {% block content %}{% endblock content %}
    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'core/plugins/jquery-3.7.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock scripts %}
  </body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <a href="{% url 'accounts:sign-up' %}" class="btn btn-primary m-3">Sign up</a>
{% endblock content %}